# Generated by Django 5.2.11 on 2026-03-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='摘要')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='封面图片')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('title', models.CharField(max_length=100, verbose_name='职位/头衔')),
                ('bio', models.TextField(verbose_name='个人简介')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub链接')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn链接')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='项目图片')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub链接')),
                ('live_url', models.URLField(blank=True, verbose_name='在线演示链接')),
                ('technologies', models.CharField(help_text='用逗号分隔', max_length=200, verbose_name='使用技术')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目展示',
                'verbose_name_plural': '项目展示',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
