# Generated by Django 5.2.11 on 2026-03-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200, verbose_name='学校名称')),
                ('degree', models.CharField(max_length=100, verbose_name='学位')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('gpa', models.CharField(blank=True, max_length=10, verbose_name='GPA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='公司名称')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('description', models.TextField(verbose_name='工作描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前职位')),
                ('technologies', models.CharField(blank=True, help_text='用逗号分隔', max_length=200, verbose_name='使用技术')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
    ]
